{% set name = "django-ses" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22ccd18a2add1e85c95df806d23382e5d977db35297622ea8dd5269a473afe51

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django
    - boto >=2.31.0
    - pytz >=2016.10
    - future >=0.16.0

test:
  commands:
    - python -c "import importlib.util; assert importlib.util.find_spec('django_ses')"

about:
  home: https://github.com/django-ses/django-ses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Django email backend for Amazon's Simple Email Service

extra:
  recipe-maintainers:
    - hadim
