{% set name = "django-ses" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54ddff0caf0aac62a6ec220a073c0214c70df58e3423685f3aa21e52b4329d34

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >1.10
    - boto3 >=1.0.0
    - pytz >=2016.10
    - future >=0.16.0

test:
  commands:
    - python -c "import importlib.util; assert importlib.util.find_spec('django_ses')"

about:
  home: https://github.com/django-ses/django-ses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Django email backend for Amazon's Simple Email Service

extra:
  recipe-maintainers:
    - hadim
